### ISSUE TITLE
Property names are improperly initial-capped

### ISSUE THREAD

**Issue by sknick** [peuter/protoc-gen-qx#19]
My previous change is improperly initial-capping property names. To fix, this is all that's needed:

![image](https://user-images.githubusercontent.com/6498506/158712235-3e96d138-6df6-4288-9108-deac59b69141.png)

(I'd submit a PR, but my master is past your latest commit and I don't want to fool with trying to work out the source control nonsense to get it in there.)

**Comment by peuter** [comment]
But you already added that change to the open PR, was that an accident?

**Comment by sknick** [comment]
Ya, I made a comment over there. I've been committing all my changes to master in my fork for expediency, so you're getting all of it. I need to clean up some things and get you a proper PR that addresses your concerns. I'd still suggest we get this fix in now though.

**Comment by peuter** [comment]
Just a tip for such quick fixes. You can open a browser IDE (VSCode in the browser) when you press the `.`  button on your keyboard when you have opened a github project page in that browser. Then you can edit any file directly in the browser and commit it. Just like you do it locally with vscode.

**Comment by sknick** [comment]
I was getting permission denied when trying to create a branch in your repo.
