### ISSUE TITLE
Use of double produces an undefined type error

### ISSUE THREAD

**Issue by sknick** [peuter/protoc-gen-qx#26]
Looks like the use of `double` in a proto message produces an error. Example message:

```
message GetLocalInfoRequest {
  double lat = 1;
  double lon = 2;
}
```

Compilation result:

```
undefined type: {
  name: 'lat',
  number: 1,
  label: 1,
  type: 1,
  typeName: undefined,
  extendee: undefined,
  defaultValue: undefined,
  oneofIndex: undefined,
  jsonName: 'lat',
  options: undefined,
  proto3Optional: undefined
} proto.raceday.v3.GetLocalInfoRequest
undefined type: {
  name: 'lon',
  number: 2,
  label: 1,
  type: 1,
  typeName: undefined,
  extendee: undefined,
  defaultValue: undefined,
  oneofIndex: undefined,
  jsonName: 'lon',
  options: undefined,
  proto3Optional: undefined
} proto.raceday.v3.GetLocalInfoRequest
```

**Comment by peuter** [comment]
Ok it seems as if the type has never been used before and did not work. The type mapping was wrong. I created a PR to fix this. Could you please try if it works for you, I cen only check if it compiles but I do not have a real example with `double` to test it in a real application. See #27 

I also updated the external dependencies in the project, also worth a test in a real environment.

**Comment by sknick** [comment]
I still owe you updates on PR #20, so let me get those addressed so I can get my fork back in sync and then I'll test this.
